name: 'Configure AWS'
description: 'Login to various AWS Accounts within Redesign Health'
inputs:
  aws-access-key-id:
    required: true
    description: 'Core cross-account IAM User access key id'
  aws-secret-access-key:
    required: true
    description: 'Core cross-account IAM User secret access key'
  aws-region:
    required: true
    description: 'The aws region to push to'
    default: us-east-1
  aws-account:
    required: true
    description: 'The aws account to push to'
    options:
      - core
      - prod
      - dev
      - staging
outputs:
  aws-account-id:
    description: 'AWS Account ID corresponding to aws-account'
    value: ${{ steps.aws-account-id.outputs.AWS_ACCOUNT_ID }}
runs:
  using: 'composite'
  steps:
    - name: Get AWS Account ID
      id: aws-account-id
      shell: bash
      run: |
        AWS_ACCOUNT_ID=$(${{ github.action_path }}/get-aws-account-id.sh ${{ inputs.aws-account }})
        echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        # We have a shared aws IAM role across our AWS accounts
        role-to-assume: arn:aws:iam::${{ steps.aws-account-id.outputs.AWS_ACCOUNT_ID }}:role/design-system-github-actions
        role-skip-session-tagging: true
        role-duration-seconds: 900
        mask-aws-account-id: false
        
