= Company API

Accelerate company time-to-market through software and hardware solutions.

== Authentication
Requests are made using the https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes[Bearer authentication scheme].

JSON Web Tokens (JWTs) are generated using https://developers.google.com/identity/protocols/oauth2/native-app[GoogleID].

TIP: Dev JWTs can be generated by visiting https://oauth.redesignhealth.com

[source, console, subs=attributes+]
----
$ curl -h 'Authorization: bearer token.value.goes-here` {service-host}/company
----

== Impersonation

NOTE: Impersonation requires the `ROLE_SUPER_ADMIN` role.
You'll receive a `401` if you attempt to impersonate without this role.

Impersonation allows you to make API calls on behalf of another account.

This is helpful for troubleshooting issues another person is experiencing without
needing their credentials.

You can impersonate by providing an email in the `RH-Impersonation-Email` header.

----
RH-Impersonation-Email: jane.doe@example.com
----

Below is an example of impersonating `jane.doe@example.com` and their view of the company list.
[source, console, subs=attributes+]
----
$ curl -h 'RH-Impersonation-Email: jane.doe@example.com' -h 'Authorization: bearer token.value.goes-here' {service-host}/company
----

== Access Control
Access is granted through a combination of xref:person.adoc[Person] roles and xref:company.adoc[Company] membership.

There are five `Role` s

* `ROLE_SUPER_ADMIN` - Able to impersonate other accounts and perform `ROLE_RH_ADMIN` taks
* `ROLE_RH_ADMIN` - Full access to all resources
* `ROLE_RH_USER` - Able to view company members and perform `ROLE_OP_CO_USER` tasks
* `ROLE_OP_CO_USER` -  Able to request company infrastructure and perform `ROLE_OP_CO_USER` tasks
* `ROLE_OP_CO_CONTRACTOR` - Able to view company details, request company members

`Roles` are granted through xref:person.adoc#_add_role[Add Role].

In order to interact with a company, a `Person` must also be affiliated with that company.

NOTE: `ROLE_RH_USER`, `ROLE_OP_CO_USER`, and `ROLE_OP_CO_CONTRACTOR` require company membership.

Membership is granted through xref:company.adoc#_add_member[Add Member].

=== Permission Matrix

Below are tables to help you get a better idea of what each
role has access to. If you'd like to understand role requirements for
a given endpoint, check out the specific endpoint's documentation (xref:company.adoc#_get[GET /company])


==== Asset
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| Upload
| ✅
| ✅
| ✅
| ✅

|===

==== Person
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ❌
| ❌
| ✅
| ✅

| Manage
| ❌
| ❌
| ❌
| ✅

| Grant/revoke roles
| ❌
| ❌
| ❌
| ✅
|===

==== Company
NOTE: All interactions with these endpoints require company membership for non-admin roles.
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ✅
| ✅
| ✅
| ✅

| Manage
| ❌
| ❌
| ❌
| ✅

| Create
| ❌
| ❌
| ❌
| ✅

| Grant/revoke membership
| ❌
| ✅
| ✅
| ✅
|===

==== Infrastructure Request
NOTE: All interactions with these endpoints require company membership for non-admin roles.

[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ✅
| ✅
| ✅
| ✅

| Request
| ❌
| ✅
| ✅
| ✅
|===

==== Form Definitions
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ✅
| ✅
| ✅
| ✅

| Manage
| ❌
| ❌
| ❌
| ✅
|===

==== Library
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ✅
| ✅
| ✅
| ✅

| Manage
| ❌
| ❌
| ❌
| ✅
|===

==== Research
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ✅
| ✅
| ✅
| ✅

| Manage
| ❌
| ❌
| ✅
| ✅
|===

==== Vendor
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ✅
| ✅
| ✅
| ✅

| Manage
| ❌
| ❌
| ❌
| ✅
|===

==== Company Vendor
[cols="1,1,1,1,1"]
|===
|Action | Company Contractor | Company User | RH User | Admin

| View
| ✅
| ✅
| ✅
| ✅

| Manage
| ✅
| ✅
| ✅
| ✅
|===

== Pagination
Each `query` endpoint (ex. xref:company.adoc#_query[GET /company]) supports pagination.

The following query parameters are used to control results returned:

* `?page` - which page to retrieve (starts at `0`)
* `?size` - how many elements to retrieve

Here's an example of fetching companies #21-40
[source, console, subs=attributes+]
----
$ curl {service-host}/company?page=1&size=20
----
Metadata about the results will be included in each response

* `size` - the amount of elements fetched (this may be smaller than the `?size` requested)
* `totalElements` - how many elements exist in total
* `totalPages` - how many pages exist based on the requested size
* `number` - the current page you are on (this is the same as `?page`)

[source, json]
----
{
  "page": {
    "size": 20,
    "totalElements": 200,
    "totalPages": 10,
    "number": 1
  }
}
----

HAL links are included to help you navigate across pages (e.g. if you requested the last elements available, `next` and
`last` will be omitted).  All query parameters are preserved in these links.

[source, json, subs=attributes+]
----
{
  "links": [{
    "rel": "first",
    "href": "{service-host}/company?page=0&size=20"
  }, {
    "rel": "next",
    "href": "{service-host}/company?page=2&size=20"
  }, {
    "rel": "pervious",
    "href": "{service-host}/company?page=0&size=20"
  }, {
    "rel": "last",
    "href": "{service-host}/company?page=9&size=20"
  }]
}
----

== Field Expansion
Some of our APIs support field expansion for child entities. Each operation below includes a list of available expansion
options. Field expansion can be accomplished through the query parameter `?expand`.

[source, console, subs=attributes+]
----
$ curl {service-host}/company?expand=members
----
Multiple `?expand` parameters can be provided to expand multiple fields

[source, console, subs=attributes+]
----
$ curl {service-host}/company?expand=members&expand=forms
----

== OpenAPI Definition

OpenAPI definition: {service-host}/public/open-api

TIP: The OpenAPI definition file can be used to generate Postman collections, API clients, and more.

Swagger: {service-host}/public/swagger

== APIs
include::asset.adoc[]
include::categories.adoc[]
include::ceos.adoc[]
include::company.adoc[]
include::company-vendor.adoc[]
include::consent.adoc[]
include::expert-note.adoc[]
include::form-definition.adoc[]
include::infrastructure-request.adoc[]
include::library.adoc[]
include::library-content.adoc[]
include::person.adoc[]
include::research.adoc[]
include::research-article.adoc[]
include::vendor.adoc[]
include::ip-marketplace.adoc[]





