export const additionalPatientSegmentOptions = [
  'GenPop',
  'GenZ',
  'Millennials',
  'GenX',
  'Boomers+',
  'Urban',
  'Rural',
  'Surburban',
  '$50K and below',
  '$50-$100K',
  '$100K and above',
  'Male',
  'Female',
  'Nonbinary',
  'Black',
  'Caucasian',
  'Hispanic',
  'Asian',
  'Full-time employed',
  'Part-time exployed',
  'Retired',
  'Employer-provided insurance',
  'Private insurance',
  'Public insurance',
  'Uninsured',
  'Small (>250)',
  'Medium (251-1000',
  'Large (1000-2999)',
  'Very large (>3000',
  'Self employed'
]
