export const researchServiceOptions = [
  'Archetype identification',
  'Churn analysis',
  'Concept test',
  'Customer satisfaction (CSAT) analysis',
  'Feature prioritization',
  'Funnel optimization',
  'General insights',
  'Growth insights',
  'Hypothesis in/Validation',
  'Iterative prototype test',
  'Landing page test',
  'Landscape mapping',
  'Literature review',
  'Market segment',
  'Naming test',
  'New feature development',
  'New promoter score (NPS) analysis',
  'Opportunity identification',
  'Pain point identification',
  'Pricing analysis',
  'Usability test',
  'User journey mapping',
  'Value prop test',
  'Website audit',
  '"How might we" Workshop'
]
