// Date: 2023-8-21
// Author: Generated by GoCodeo.

import { FormProvider, useForm } from 'react-hook-form'
import {
  fireEvent,
  mocks,
  render,
  screen
} from '@redesignhealth/shared-utils-jest'

import { CompanyForm, OptionsProps } from './company-form'

describe('CompanyForm', () => {
  mocks.matchMedia('any', false)
  const options: OptionsProps[] = [
    { value: 'option1', label: 'Option 1' },
    { value: 'option2', label: 'Option 2' }
  ]

  const conceptOptions: OptionsProps[] = [
    { value: 'concept1', label: 'Concept 1' },
    { value: 'concept2', label: 'Concept 2' }
  ]

  const themeOptions: OptionsProps[] = [
    { value: 'theme1', label: 'Theme 1' },
    { value: 'theme2', label: 'Theme 2' }
  ]

  const renderComponent = (props = {}) => {
    const Wrapper = () => {
      const methods = useForm()
      return (
        <FormProvider {...methods}>
          <CompanyForm
            isPending={false}
            isSuccess
            options={options}
            conceptOptions={conceptOptions}
            themeOptions={themeOptions}
            {...props}
          />
        </FormProvider>
      )
    }
    render(<Wrapper />)
  }

  afterEach(() => {
    jest.clearAllMocks()
  })

  it('renders the form correctly', () => {
    renderComponent()
    expect(screen.getByLabelText('Company #')).toBeInTheDocument()
    expect(screen.getByLabelText('Legal name')).toBeInTheDocument()
    expect(screen.getByLabelText('Stage')).toBeInTheDocument()
    expect(screen.getByLabelText('Description')).toBeInTheDocument()
  })

  it('renders the concept select when stageField is "NEW_CO"', () => {
    renderComponent()
    fireEvent.change(screen.getByLabelText('Stage'), {
      target: { value: 'NEW_CO' }
    })
    expect(screen.getByLabelText('Concept')).toBeInTheDocument()
  })

  it('renders the theme select when stageField is "CONCEPT"', () => {
    renderComponent()
    fireEvent.change(screen.getByLabelText('Stage'), {
      target: { value: 'CONCEPT' }
    })
    expect(screen.getByLabelText('Theme')).toBeInTheDocument()
  })

  it('renders the conflicts select when stageField is "NEW_CO"', () => {
    renderComponent()
    fireEvent.change(screen.getByLabelText('Stage'), {
      target: { value: 'NEW_CO' }
    })
    expect(screen.getByLabelText('Conflicts')).toBeInTheDocument()
  })

  it('renders the conflicts select when stage is "OP_CO"', () => {
    renderComponent()
    fireEvent.change(screen.getByLabelText('Stage'), {
      target: { value: 'OP_CO' }
    })
    expect(screen.getByLabelText('Conflicts')).toBeInTheDocument()
  })

  it('renders the fundraising stage radio group when stage is "OP_CO"', () => {
    renderComponent()
    fireEvent.change(screen.getByLabelText('Stage'), {
      target: { value: 'OP_CO' }
    })
    expect(
      screen.getByRole('group', { name: 'Fundraising Stage' })
    ).toBeInTheDocument()
  })

  it('disables the form controls when isPending is true', () => {
    renderComponent({ isPending: true })
    expect(screen.getByLabelText('Internal name (required)')).toBeDisabled()
    expect(screen.getByLabelText('Company #')).toBeDisabled()
    expect(screen.getByLabelText('Legal name')).toBeDisabled()
    expect(screen.getByLabelText('Stage')).toBeDisabled()
    expect(screen.getByLabelText('Description')).toBeDisabled()
  })

  it('updates the count when description field value changes', () => {
    renderComponent()
    const descriptionTextarea = screen.getByLabelText('Description')
    fireEvent.change(descriptionTextarea, {
      target: { value: 'Test description' }
    })
    expect(screen.getByText('484 characters left')).toBeInTheDocument()
  })
})
