ALTER TYPE ceo_business_focus_area RENAME VALUE 'CARDIOLOGY_CARDIOVASCULAR' TO 'CARDIOLOGY';
ALTER TYPE ceo_business_focus_area RENAME VALUE 'HEALTH_CHILD_DEVELOPMENT' TO 'CHILD_DEVELOPMENT';
ALTER TYPE ceo_business_focus_area RENAME VALUE 'APM_INCENTIVES' TO 'APM_INCENTIVES_DESIGN';
ALTER TYPE ceo_business_focus_area RENAME VALUE 'DESIGN_BENEFITS' TO 'BENEFITS';
ALTER TYPE ceo_business_focus_area ADD VALUE 'CARDIOVASCULAR_HEALTH';
