CREATE TYPE ceo_business_type AS ENUM ('B2B', 'B2B2C', 'D2C');
CREATE TYPE ceo_healthcare_sector AS ENUM ('BIOPHARMA_AND_DEVICE', 'PEDIATRICS', 'WELLNESS_AND_PREVENTION', 'BENEFIT_ENHANCEMENT', 'SPECIALTY_CARE', 'CHRONIC_CARE_MANAGEMENT', 'ACUTE_CARE', 'POSTS_ACUTE_CARE',  'HEALTHY_AGING',  'CARE_ENABLEMENT');
CREATE TYPE ceo_visible AS ENUM ('OPT_IN', 'OPT_OUT');

