CREATE TYPE ip_marketplace_speciality AS ENUM(
'ALLERGY_AND_IMMUNOLOGY',
'ANESTHESIOLOGY',
'CARDIOLOGY',
'DERMATOLOGY',
'EMERGENCY_MEDICINE',
'ENDOCRINOLOGY',
'FAMILY_MEDICINE',
'GASTROENTEROLOGY',
'GERIATRICS',
'HEMATOLOGY',
'INFECTIOUS_DISEASE',
'INTERNAL_MEDICINE',
'MEDICAL_GENETICS',
'NEPHROLOGY',
'NEUROLOGY',
'OBSTETRICS_AND_GYNECOLOGY_OB_GYN',
'OPHTHALMOLOGY',
'ORTHOPEDICS',
'OTOLARYNGOLOGY_ENT',
'PALLIATIVE_MEDICINE',
'PATHOLOGY',
'PEDIATRICS',
'PHYSICAL_MEDICINE_AND_REHABILITATION',
'PLASTIC_SURGERY',
'PSYCHIATRY',
'PULMONOLOGY',
'RADIATION_ONCOLOGY',
'RADIOLOGY',
'RHEUMATOLOGY',
'SLEEP_MEDICINE',
'SPORTS_MEDICINE',
'UROLOGY'
);

CREATE TYPE ip_marketplace_technology_type AS ENUM(
'MEDICAL_DEVICES',
'DIAGNOSTIC_TOOLS',
'SOFTWARE_APPLICATIONS',
'ALGORITHMS_AND_ANALYTICS',
'CLINICAL_CARE_MODELS',
'WEARABLE_AND_REMOTE_MONITORING_DEVICES',
'HEALTH_INFORMATION_SYSTEMS',
'OTHER'
);

CREATE TYPE ip_marketplace_technology_level_of_maturity AS ENUM(
'TRIAL_VALIDATION_COMPLETED',
'ANIMAL_STUDY',
'BENCH_TESTING',
'FIRST_IN_HUMAN',
'CLINICAL_DATA',
'PROTOTYPE',
'N_A'
);

CREATE TYPE ip_marketplace_freedom_to_operate_certification AS ENUM(
'YES',
'NO',
'PENDING'
);

CREATE TYPE ip_marketplace_patent_status AS ENUM(
'PATENTED',
'NON_PATENTED',
'PENDING',
'PROVISIONAL',
'OTHER'
);

CREATE TYPE ip_marketplace_patent_geography_validity AS ENUM(
'US',
'EUROPE',
'ASIA',
'OTHER'
);

CREATE TYPE ip_marketplace_preferred_terms AS ENUM(
'EQUITY',
'ROYALTIES',
'LICENSURE',
'ACQUISITION',
'OTHER'
);

CREATE TYPE ip_marketplace_track_contact_info AS ENUM(
'REQUESTED_CONTACT_INFO',
'RELEASED_CONTACT_INFO'
);

